version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: qr_shirts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ../migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
